name: CI
on:
  - push
  - pull_request
env:
  JULIA_NUM_THREADS: 2
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - name: install Documenter and TrypImages
        run: >
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=docs -e 'import Pkg; Pkg.add("Documenter"); using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
          && echo "TESTS_SUCCESSFUL=true" >> $GITHUB_ENV          
      - uses: julia-actions/cache@v1
      - name: make the doc
        continue-on-error: true
        run: >
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --color=yes --project=monorepo --project=docs docs/make.jl
          && echo "TESTS_SUCCESSFUL=true" >> $GITHUB_ENV



        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}